# ASP.NET Core (.NET Framework)

trigger:
- master

pool:
  vmImage: 'windows-latest'



steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'TestConnection'
    organization: '210215-usf-net'
    scannerMode: 'MSBuild'
    projectKey: '210215-USF-NET_Frank_Wang-P1'
    projectName: 'Frank_Wang-p1'
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: $(solution)
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    zipAfterPublish: true
    publishWebProjects: true
    
    
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(67ebb982-6c62-47c0-91e2-decd4b6b08c6)'
    appType: 'webApp'
    WebAppName: 'StoreFW'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    

